name: Run Girolle

on:
  workflow_call:

jobs:
  run-girolle:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to upload release assets

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt install -y libprotoc-dev protobuf-compiler build-essential gcc pkg-config libssl-dev unzip wget cmake openssl libpq-dev
      - uses: actions/checkout@v5
      - name: Checkout catenary-backend
        uses: actions/checkout@v4
        with:
          repository: catenarytransit/catenary-backend
          path: catenary-backend

      - name: Checkout transitland-atlas
        uses: actions/checkout@v4
        with:
          repository: catenarytransit/transitland-atlas
          path: transitland-atlas

      - name: Set up Rust
        run: rustup toolchain install stable

      - name: Compiler cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "catenary-backend"

      - name: Compile girolle
        run: cargo build --release --bin girolle
        working-directory: ./catenary-backend

      - name: Run girolle
        run: ./catenary-backend/target/release/girolle --transitland ./transitland-atlas --outfile girolle-results.txt

      - name: Upload girolle results to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload latest girolle-results.txt --clobber

      # Step 1: Conditionally modify hello.txt
      - name: Check inactivity and update hello.txt
        run: |
          LAST_COMMIT_TIME=$(git log -1 --format=%ct)
          CURRENT_TIME=$(date +%s)
          DIFF=$((CURRENT_TIME - LAST_COMMIT_TIME))
          THIRTY_DAYS=2592000

          if [ $DIFF -gt $THIRTY_DAYS ]; then
            echo "Last commit was over 30 days ago. Updating hello.txt."
            date > hello.txt
          else
            echo "Last commit was recent. Skipping file update."
          fi

      # Step 2: Commit and push using the community action
      - name: Push keep-alive commit if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: automated keep-alive update"
          file_pattern: "hello.txt"
          commit_user_name: "catenary-automated-workflow"
          commit_user_email: "catenary-automated-github-workflow@catenarymaps.org"
          commit_author: "catenary-automated-workflow <catenary-automated-github-workflow@catenarymap
